### ISSUE TITLE
dropbox file deleted

### ISSUE THREAD

**Issue by jonnyhotchkiss** [pumodi/open-samples#15]
Hi! Is this still available?
Do we now just use the github download link, or doesn't that contain everything that was available via the dropbox link?
Thanks!

**Comment by pumodi** [comment]
Hey Jonny, thanks for the heads up on this. We had a shake up with our dropbox and subscription costs. I must've missed updating the link. I'll get that taken care of today and ping you when it's fixed. Sorry about that!

**Comment by pumodi** [comment]
@jonnyhotchkiss should be all fixed! New link is in the readme and also linked here:
https://www.dropbox.com/scl/fi/wsr7wquf76uoanr2in5sw/Open-Samples_v107.zip?rlkey=9akx88jupsacrllvn3ezpoa9a&dl=0
